CREATE TABLE IF NOT EXISTS Energy(
	name VARCHAR(12) PRIMARY KEY
);
DELETE FROM Energy;
INSERT INTO Energy VALUES('ANY');
INSERT INTO Energy VALUES('GASOLINE');
INSERT INTO Energy VALUES('DIESEL');
INSERT INTO Energy VALUES('ELECTRIC');
INSERT INTO Energy VALUES('GAS');

CREATE TABLE IF NOT EXISTS Gearbox(
	name VARCHAR(12) PRIMARY KEY
);
DELETE FROM Gearbox;
INSERT INTO Gearbox VALUES('ANY');
INSERT INTO Gearbox VALUES('AUTOMATIC');
INSERT INTO Gearbox VALUES('MANUAL');
INSERT INTO Gearbox VALUES('SEQUENTIAL');

CREATE TABLE IF NOT EXISTS Civility(
	name VARCHAR(6) PRIMARY KEY
);
DELETE FROM Civility;
INSERT INTO Civility VALUES('MISTER');
INSERT INTO Civility VALUES('MISS');
INSERT INTO Civility VALUES('OTHER');

CREATE TABLE IF NOT EXISTS AnnouncementType(
	name VARCHAR(4) PRIMARY KEY
);
DELETE FROM AnnouncementType;
INSERT INTO AnnouncementType VALUES('ANY');
INSERT INTO AnnouncementType VALUES('RENT');
INSERT INTO AnnouncementType VALUES('SELL');


CREATE TABLE IF NOT EXISTS NotificationType(
	name VARCHAR(8) PRIMARY KEY
);
DELETE FROM NotificationType;
INSERT INTO NotificationType VALUES('ALERT');
INSERT INTO NotificationType VALUES('MESSAGE');

CREATE TABLE IF NOT EXISTS User(
	id INTEGER PRIMARY KEY,
	email VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL,
	address VARCHAR(256) NOT NULL,
	zip VARCHAR(256) NOT NULL,
	city VARCHAR(256) NOT NULL,
	country VARCHAR(256) NOT NULL,
	phone VARCHAR(256) NOT NULL,
	isProfessional BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS ParticularUser(
	id INTEGER PRIMARY KEY,
	civility VARCHAR(6) NOT NULL,
	firstName VARCHAR(256) NOT NULL,
	lastName VARCHAR(256) NOT NULL,
	FOREIGN KEY(id) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS ProfessionalUser(
	id INTEGER PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	siret VARCHAR(256) NOT NULL,
	isPremium BOOLEAN NOT NULL,
	FOREIGN KEY(id) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Announcement(
	id INTEGER PRIMARY KEY,
	type VARCHAR(4) NOT NULL,
	brand VARCHAR(256) NOT NULL,
	model VARCHAR(256) NOT NULL,
	price INTEGER NOT NULL,
	address VARCHAR(256) NOT NULL,
	zip VARCHAR(256) NOT NULL,
	city VARCHAR(256) NOT NULL,
	country VARCHAR(256) NOT NULL,
	kilometers INTEGER NOT NULL,
	year INTEGER NOT NULL,
	technicalControl BOOLEAN NOT NULL,
	energy VARCHAR(12) NOT NULL,
	gearbox VARCHAR(12) NOT NULL,
	exteriorColor VARCHAR(256) NOT NULL,
	interiorColor VARCHAR(256) NOT NULL,
	doors INTEGER NOT NULL,
	places INTEGER NOT NULL,
	formerOwnerCount INTEGER NOT NULL,
	power INTEGER NOT NULL,
	din INTEGER NOT NULL,
	co2 FLOAT(2) NOT NULL,
	consumption FLOAT(2) NOT NULL,
	author INTEGER NOT NULL,
	isEnhance BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (type) REFERENCES AnnouncementType(name),
	FOREIGN KEY (energy) REFERENCES Energy(name),
	FOREIGN KEY (gearbox) REFERENCES Gearbox(name),
	FOREIGN KEY (author) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Alert(
	id INTEGER PRIMARY KEY,
	user INTEGER,
	enabled BOOLEAN NOT NULL DEFAULT FALSE,
	search VARCHAR(256),
	type VARCHAR(4) NOT NULL,
	brand VARCHAR(256),
	model VARCHAR(256),
	maxPrice INTEGER,
	minPrice INTEGER DEFAULT 0,
	maxKilometers INTEGER,
	minYear INTEGER DEFAULT 1971,
	maxYear INTEGER,
	technicalControlRequired BOOLEAN DEFAULT FALSE,
	energy VARCHAR(12),
	gearbox VARCHAR(12),
	minPlaces INTEGER DEFAULT 1,
	announcer INTEGER,
	FOREIGN KEY (user) REFERENCES User(id),
	FOREIGN KEY (type) REFERENCES AnnouncementType(name),
	FOREIGN KEY (energy) REFERENCES Energy(name),
	FOREIGN KEY (gearbox) REFERENCES Gearbox(name),
	FOREIGN KEY (announcer) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Favorite(
	id INTEGER PRIMARY KEY,
	user INTEGER NOT NULL,
	announcement INTEGER NOT NULL,
	FOREIGN KEY (user) REFERENCES User(id),
	FOREIGN KEY (announcement) REFERENCES Announcement(id)
);

CREATE TABLE IF NOT EXISTS Message(
	id INTEGER PRIMARY KEY,
	announcement INTEGER NOT NULL,
	source INTEGER NOT NULL,
	destination INTEGER NOT NULL,
	text VARCHAR(512) NOT NULL,
	dateTime DATETIME NOT NULL,
	FOREIGN KEY (announcement) REFERENCES Announcement(id),
	FOREIGN KEY (source) REFERENCES User(id),
	FOREIGN KEY (destination) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Notification(
	id INTEGER PRIMARY KEY,
	dateTime DATETIME NOT NULL,
	type VARCHAR(8) NOT NULL,
	data INTEGER NOT NULL,
	user INTEGER NOT NULL,
	seen BOOLEAN NOT NULL DEFAULT FALSE,
	notified BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (user) REFERENCES User(id)
);
